[package]
name = "guessing_game"
version = "0.1.0"
authors = ["Michael Stallings <stall84@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
