[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
num-complex = "0.2.1"
crossterm = "0.17.5"
rusty_audio = "1.1.4"