name: "Rustfmt check"

on:
  push:
  pull_request:

jobs:
  # Check formatting with rustfmt
  formatting:
    name: rustfmt all repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Ensure rustfmt is installed and setup problem matcher
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Rustfmt Check
        run: find . -type f -name "*.rs" | xargs rustfmt --check
